resolver: lts-14.27

packages:
- .
- hs-generator
#- ../hs-yesod-model-generator

extra-deps:
- git: https://github.com/agreif/hs-yesod-model-generator.git
  commit: 9e6b03ab791d64450d8b38913570bd6959e304ef
- pwstore-fast-2.4.4@sha256:9b6a37510d8b9f37f409a8ab3babac9181afcaaa3fce8ba1c131a7ed3de30698,1351

nix:
  enable: true
  pure: false
  packages:
    - zlib
    - bzip2
    - postgresql
